### ISSUE TITLE
看不懂

### ISSUE THREAD

**Issue by okkkkoo** [BaiXinSuper/Universe#2]
![fh2gkkg1](https://user-images.githubusercontent.com/77115336/151662733-1796e74d-d00e-4552-aaf6-51bb5d7fd745.png)

**Comment by BaiXinSuper** [comment]
open the options -> language -> English
你可以嘗試自己製作繁體翻譯然後上傳在我們的頻道
我可能在年後製作繁體翻譯，請耐心等待

**Comment by okkkkoo** [comment]
解決了 Thx
